apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 5
      parallelism: 5
      template:
        spec:
          containers:
          - name: my-cron-job
            image: ubuntu
            command: ["/bin/sh", "-c", "echo parallel job"]
          restartPolicy: OnFailure
