apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user: 'dXNlcg=='
  pass: 'cGFzcw=='

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - secretRef:
        name: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always

