apiVersion: v1
kind: ConfigMap
metadata:
  name: first-cm
data:
  ip: "225.225.255.0"
  server: "RFID"

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
        name: first-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always

