apiVersion: v1
kind: Namespace
metadata:
  name: day1
spec:
  finalizers:
    - kubernetes


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-first
  namespace: day1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


