apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex-14
  name: ex-14
spec:
  containers:
  - image: nginx
    name: ex-14
    command: ["sleep"]
    args: ["3600"]
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
