apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex-3
  name: ex-3
spec:
  containers:
  - image: nginx:latest
    name: ex-3-nginx
    ports:
    - containerPort: 80
    resources: {}
  - image: redis
    name: ex-3-redis
    ports:
    - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
