apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex-14
  name: ex-14
spec:
  containers:
  - image: busybox
    name: ex-14
    ports:
    - containerPort: 80
    args:
    - sleep
    - "3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always

