apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex-13
  name: ex-13
spec:
  containers:
  - image: nginx
    name: ex-13
    ports:
    - containerPort: 80
    env:
    - name: tier
      value: web
    - name: enviroment
      value: dev
  dnsPolicy: ClusterFirst
  restartPolicy: Always


