apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-3
  name: ex-3
spec:
  containers:
  - image: nginx
    name: ex-3
    resources: {}
    ports:
    - containerPort: 80
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
