apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - image: ubuntu
        name: job
        command: ["/bin/sh", "-c", "echo It is my first job"]
      restartPolicy: Never
