apiVersion: batch/v1
kind: Job
metadata:
  name: activedead-job
spec:
  backoffLimit: 1
  completions: 5
  parallelism: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - image: ubuntu
        name: job
        command: ["/bin/sh", "-c", "echo active deadline seconds"]
      restartPolicy: Never
