apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  backoffLimit: 1
  completions: 6
  parallelism: 3
  template:
    spec:
      containers:
      - image: ubuntu
        name: job
        command: ["/bin/sh", "-c", "echo parallel job"]
      restartPolicy: Never
