apiVersion: batch/v1
kind: Job
metadata:
  name: second-job
spec:
  backoffLimit: 1
  completions: 5
  template:
    spec:
      containers:
      - image: ubuntu
        name: job
        command: ["/bin/sh", "-c", "echo second job"]
      restartPolicy: Never
