apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-reader

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-binding-role
subjects:
- kind: ServiceAccount
  name: global-reader
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-role
  apiGroup: rbac.authorization.k8s.io
