apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader2
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
