apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-secrets
subjects:
- kind: ServiceAccount
  name: reader
  namespace: default
roleRef:
  kind: Role
  name: reader-secrets
  apiGroup: rbac.authorization.k8s.io
