apiVersion: v1
kind: PersistentVolume
metadata:
  name: ex-1-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /ex-1-dir
  volumeMode: Filesystem 
