apiVersion: v1
kind: PersistentVolume
metadata:
  name: varlog-pv
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /ex-17
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: varlog-pvc
spec:
  dataSource:
    name: varlog-pv
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
