apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /ex-11
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  dataSource:
    name: mysql-pv
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql:8.0.31
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: linuxtips
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: mysql-pvc-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-pvc-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
