apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /ex-13
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
spec:
  dataSource:
    name: psql-pvc
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
