apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
spec:
  dataSource:
    name: psql-pvc
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    run: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  containers:
  - image: postgres:14
    name: postgres
    ports:
    - containerPort: 5432
    envFrom:
    - configMapRef:
        name: postgres-secret
    volumeMounts:
    - name: postgres-pvc-storage
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-pvc-storage
    persistentVolumeClaim:
      claimName: psql-pvc
