apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-empty
  name: nginx-empty
spec:
  containers:
  - image: nginx
    name: nignx-empty
    volumeMounts:
    - mountPath: /data/nginx
      name: nginx-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nginx-storage
    emptyDir: {}
