apiVersion: v1
kind: PersistentVolume
metadata:
  name: ex-1-pv
spec:
  storageClassName: ""
  capacity:
    sotager: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /ex-1-dir
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task1-pvc
spec:
  storageClassName: ""
  dataSource:
    name: ex1-pv
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
