apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex-4-pod
  name: ex-4-pod
spec:
  containers:
  - image: redis
    name: ex-4-pod
    volumeMounts:
    - mountPath: /data/redis
      name: ex-4-pod
  volumes:
  - name: ex-4-pod
    emptyDir:
      sizeLimit: 500Mi
