apiVersion: v1
kind: PersistentVolume
metadata:
  name: html-index-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-index-pvc
spec:
  dataSource:
    name: html-index-pv
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-html
  name: test-html
spec:
  containers:
  - image: nginx
    name: nginx-html
    volumeMounts:
    - name: using-html-index-pvc
      mountPath: /usr/share/nginx/html
  - image: busybox
    name: busybox
    args: 
    - while true; do date >> /html/index.html; sleep 1; done
    volumeMounts:
    - name: using-html-index-pvc
      mountPath: /html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: using-html-index-pvc
    persistentVolumeClaim:
      claimName: html-index-pvc
