apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always