apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giro
  name: giro
spec:
  containers:
  - image: nginx
    name: giro
    volumeMounts:
    - mountPath: /giropops
      name: first-empty-dir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: first-empty-dir
    emptyDir:
      sizeLimit: 256Mi
